### ISSUE TITLE
Application performance is very slow using IE

### ISSUE THREAD

**Issue by chavisa** [david-meza/park-locator#28]
Using IE, all functions on the map are very slow and sluggish response. The performance with Firefox and Chrome are fine.

**Comment by david-meza** [comment]
Unfortunately, this is a memory and performance intensive application due to all the scripting that is happening on the front-end by the Angular framework. You could say that this is an application built for the long term and for the browsers of the future. In addition, I don't really have much control over most of the functions in the map as they are controlled by Esri's API. But if you can tell me which functions, in particular, feels almost unusable on IE, I can take a look at it and improve their performance as there's always some refactoring that can be done.

**Comment by chavisa** [comment]
David, I understand. I would suggest if a user attempts to use IE they receive a message that it is not an acceptable browser or not allowed to use IE at all.
