### ISSUE TITLE
Search feature does not yield results using commn tems

### ISSUE THREAD

**Issue by chavisa** [david-meza/park-locator#29]
I am on the Class page and using the Search feature. I did a search using common terms but each time received a message there are no results. 
Terms used: Dance, class, gym, track, pool, fish, tennis, playground, volleyball, yoga, pottery, 5:30pm

[You can search by any one term.docx](https://github.com/david-meza/park-locator/files/235657/You.can.search.by.any.one.term.docx)

**Comment by david-meza** [comment]
Maybe I should clarify that the search feature only filters down existing results on the particular category you selected. The reason why that was implemented was because some categories would have hundreds of results (cards) so searching for what you wanted would very quickly let you know if what you were looking for was on the list or not.
