### ISSUE TITLE
No image for picnic shelter

### ISSUE THREAD

**Issue by chavisa** [david-meza/park-locator#30]
Under the 'Things To Do', display a Picnic Shelter (see attached). The icon does not have an image, like the others. 

[No image for picnic shelter.docx](https://github.com/david-meza/park-locator/files/235748/No.image.for.picnic.shelter.docx)

**Comment by david-meza** [comment]
This has been a known bug for a while, but unfortunately, we haven't been able to re-create it and it only happens occasionally. If you can provide us more details about your circumstances (browser, OS, maybe some steps to reproduce the bug if you have figured it out) that would be really helpful. In the meantime, I've implemented a fix on an educated guess of what I think the problem is (a clipPath layer) so lot me know if this keeps happening.
