### ISSUE TITLE
ArcGIS REST services do not work over cellular connection

### ISSUE THREAD

**Issue by david-meza** [david-meza/park-locator#37]
I've been having this issue for some time (it happened every time that I demo-ed the app to people) but I thought the app was just loading slowly and the data would take some time to come in. Today I finally understood what was happening. We are getting cross-origin errors when trying to access these REST services over cellular connection. This does not happen over wi-fi on the oaktree network or any other network outside of work. It happens on my AT&T LTE connection and I'm not sure if it's only with my carrier or any other cellular connection. Below is a screenshot of the console errors on web inspector.

![2016-05-04_13-40-03](https://cloud.githubusercontent.com/assets/11840636/15023571/08de32d4-11ff-11e6-8f82-0adb22ce4686.png)

**Comment by justingreco** [comment]
The final app will live on maps.raleighnc.gov<http://maps.raleighnc.gov>, so there won’t be cross-domain requests in the future.  Though since you are using JSONP, it shouldn’t be an issue.  Will test on Verizon, don’t think I have seen that.




On May 4, 2016, at 1:52 PM, David Meza <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been having this issue for some time (it happened every time that I demo-ed the app to people) but I thought the app was just loading slowly and the data would take some time to come in. Today I finally understood what was happening. We are getting cross-origin errors when trying to access these REST services over cellular connection. This does not happen over wi-fi on the oaktree network or any other network outside of work. It happens on my AT&T LTE connection and I'm not sure if it's only with my carrier or any other cellular connection. Below is a screenshot of the console errors on web inspector.

[2016-05-04_13-40-03]<https://cloud.githubusercontent.com/assets/11840636/15023571/08de32d4-11ff-11e6-8f82-0adb22ce4686.png>

—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub<https://github.com/david-meza/park-locator/issues/37>

“E-mail correspondence to and from this address may be subject to the North Carolina Public Records Law and may be disclosed to third parties by an authorized City or Law Enforcement official.”

**Comment by david-meza** [comment]
This also happens to my on the parks part time jobs app. Same error even though it is being accessed from http://openmaps.raleighnc.gov

**Comment by david-meza** [comment]
Apparently this only happens on my phone and with my carrier so it may be an issue with AT&T...
